# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      routes_generator:
        options:
          group: '_RoutesGroup.name'
          ignores: '**.g.dart'
          dynamic: 'Dynamic'
          routes:
            routes.dart:
              name: "routes"
              pages: "pages"
              group: '_RoutesGroup.name'
              ignores: '**/widgets/**'
            dev/routes.dart:
              prefix: "/dev"
              name: "devRoutes"
              pages: "pages"
              group: '_RoutesGroup.name'
              dynamic: false
              ignores: false
